"""initial_migration

Revision ID: 2c1d95238fdd
Revises: 
Create Date: 2024-04-13 20:07:31.479038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1d95238fdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operation'
    )
    op.create_table('collaborator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('role', sa.Enum('GERENTE', 'SUPERVISOR', 'COLABORADOR', 'EXTERNO', name='collaborator_role_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operation'
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operation'
    )
    op.create_table('material_collect_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neighborhood', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='operation'
    )
    op.create_table('truck',
    sa.PrimaryKeyConstraint('id'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plate', sa.String(length=255), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.UniqueConstraint('plate'),
    schema='operation'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role_enum'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='security'
    )
    op.create_table('material_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('collect_site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collect_site_id'], ['operation.material_collect_site.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['operation.truck.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operation'
    )
    op.create_table('storage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('ENTRADA', 'SAIDA', name='storage_history_type_enum'), nullable=False),
    sa.Column('collaborator_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['collaborator_id'], ['operation.collaborator.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['operation.material.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operation'
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('collaborator_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['operation.client.id'], ),
    sa.ForeignKeyConstraint(['collaborator_id'], ['operation.collaborator.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operation'
    )
    op.create_table('material_triage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('collaborator_id', sa.Integer(), nullable=False),
    sa.Column('material_collection_id', sa.Integer(), nullable=False),
    sa.Column('storage_history_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collaborator_id'], ['operation.collaborator.id'], ),
    sa.ForeignKeyConstraint(['material_collection_id'], ['operation.material_collection.id'], ),
    sa.ForeignKeyConstraint(['storage_history_id'], ['operation.storage_history.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operation'
    )
    op.create_table('storage_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('storage_history_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storage_history_id'], ['operation.storage_history.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['operation.transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='operation'
    )

    op.execute(
        """
        INSERT INTO security.user (name, role, email, password)
        VALUES (
            'admin', 
            'ADMIN', 
            'admin@admin.com', 
            '$2b$12$Mo90lZ8UKbWf41X/N8T.UemUUuYD.CmdSpBAIBp0v4nl/YET4W.GG'
        )
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_transaction', schema='operation')
    op.drop_table('material_triage', schema='operation')
    op.drop_table('transaction', schema='operation')
    op.drop_table('storage_history', schema='operation')
    op.drop_table('material_collection', schema='operation')
    op.drop_table('user', schema='security')
    op.drop_table('truck', schema='operation')
    op.drop_table('material_collect_site', schema='operation')
    op.drop_table('material', schema='operation')
    op.drop_table('collaborator', schema='operation')
    op.drop_table('client', schema='operation')
    # ### end Alembic commands ###
